In [1]:
import torch
torch.random.manual_seed(42)

In [20]:
n_particles = 2
n_time_steps = 5

new_log_probs = torch.log(torch.tensor([0.2, 0.3, 0.05, 0.15, 0.3]))

old_log_probs = torch.clone(new_log_probs)

adv = torch.rand(n_time_steps)

expected_loss = -1 * adv


In [23]:
print(new_log_probs)

tensor([-1.6094, -1.2040, -2.9957, -1.8971, -1.2040])


In [51]:
def compute_true_value_function(
    rewards: list, gamma: float = 0.99, standardize: bool = True
):
    """
    Compute the true value function from the rewards.

    Parameters
    ----------
    rewards : List
            A tensor of scalar tasks on which the expected value is computed.
    gamma : float (default=0.99)
            A decay factor for the value of the tasks.
    standardize : bool (default=True)
            If true, the result is standardized.

    Returns
    -------
    expected_returns : torch.Tensor (n_timesteps, )
            expected returns for each particle
    """
    true_value_function = torch.zeros(n_time_steps)
    current_value_state = torch.tensor(0)

    for i in range(n_time_steps)[::-1]:
        current_value_state = rewards[i] + current_value_state * gamma

        true_value_function[i] = current_value_state

    # Standardize the value function.
    if standardize:
        mean = torch.mean(torch.tensor(true_value_function), dim=0)
        std = torch.std(torch.tensor(true_value_function), dim=0)

        true_value_function = (true_value_function - mean) / std

    return true_value_function

In [52]:
rewards = torch.rand(n_time_steps)

value_function = compute_true_value_function(
            rewards=rewards, gamma=1, standardize=False
        )

In [56]:
rewards = torch.tensor([1,2,3,4,5])

In [57]:
discounted_return = torch.zeros
current_value = torch.tensor(0)
gamma = 1.0
for i in range(n_time_steps)[::-1]:
    current_value = current_value * gamma + rewards[i]
    discounted_return.append(current_value)
print(discounted_return[::-1])

AttributeError: 'builtin_function_or_method' object has no attribute 'append'

In [55]:
value_function

tensor([1.3810, 1.1115, 0.7527, 0.5534, 0.0062])

In [2]:
a = [200,300,400]
b = [202,298,402]
c = [200,296,404]
d = [198,294,402]
e = [196,296,400]
feature_vector = torch.Tensor([a,b,c,d,e])

In [3]:
print(feature_vector)

tensor([[200., 300., 400.],
        [202., 298., 402.],
        [200., 296., 404.],
        [198., 294., 402.],
        [196., 296., 400.]])
